"""
report_generator.py
-------------------
Module untuk membuat laporan hasil analisis Quant Behavior.
Semua komentar menggunakan ASCII agar aman untuk Notepad Windows.
"""

import pandas as pd
import numpy as np

# ============================================================
# 1. TEXT FORMATTER
# ============================================================

def format_section(title, content):
    """
    Membuat format teks rapi untuk setiap section.
    """

    line = "=" * len(title)
    text = f"{line}\n{title}\n{line}\n"

    if content is None:
        text += "No data\n"
    elif isinstance(content, str):
        text += content + "\n"
    elif isinstance(content, dict):
        for k, v in content.items():
            text += f"{k}: {v}\n"
    elif isinstance(content, list):
        for item in content:
            text += f"{item}\n"
    elif isinstance(content, pd.DataFrame):
        text += content.to_string(index=False) + "\n"
    else:
        text += str(content) + "\n"

    return text + "\n"


# ============================================================
# 2. REPORT BUILDER
# ============================================================

def build_report(event_summary=None,
                 regime_summary=None,
                 transition_summary=None,
                 ce_table=None,
                 best_strategies=None):
    """
    Menggabungkan seluruh komponen laporan menjadi satu string.
    """

    report = ""
    report += format_section("QUANT BEHAVIOR REPORT", "Generated by Quant Behavior Engine")

    report += format_section("EVENT SUMMARY", event_summary)
    report += format_section("REGIME SUMMARY", regime_summary)
    report += format_section("TRANSITION SUMMARY", transition_summary)
    report += format_section("CONDITIONAL EXPECTANCY TABLE", ce_table)
    report += format_section("BEST STRATEGIES", best_strategies)

    return report


# ============================================================
# 3. SAVE REPORT TO FILE
# ============================================================

def save_report(text_report, output_path="quant_behavior_report.txt"):
    """
    Menyimpan laporan ke file TXT.
    """

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text_report)

    return output_path


# ============================================================
# 4. OPTIONAL: CSV EXPORT
# ============================================================

def save_ce_table_csv(ce_table, output_path="ce_table.csv"):
    """
    Menyimpan Conditional Expectancy table ke CSV.
    """

    if ce_table is None or not isinstance(ce_table, pd.DataFrame):
        return None

    ce_table.to_csv(output_path, index=False)
    return output_path


def save_strategy_csv(best_strategies, output_path="best_strategies.csv"):
    """
    Menyimpan daftar strategi terbaik ke CSV.
    """

    if best_strategies is None:
        return None

    if isinstance(best_strategies, list):
        df = pd.DataFrame(best_strategies)
    elif isinstance(best_strategies, pd.DataFrame):
        df = best_strategies
    else:
        return None

    df.to_csv(output_path, index=False)
    return output_path


# ============================================================
# SELF TEST
# ============================================================

if __name__ == "__main__":
    # Dummy data for test
    event_summary = {
        "impulse": 25,
        "retracement": 40,
        "consolidation": 35
    }

    regime_summary = {
        "trend": 60,
        "range": 30,
        "squeeze": 10
    }

    transition_summary = {
        "impulse_trend": [("retracement_trend", 0.45), ("consolidation_range", 0.30)],
        "range_range": [("impulse_trend", 0.40)]
    }

    ce_table = pd.DataFrame([
        {"condition": "bullish_candle", "ce": 0.002, "winrate": 0.55, "samples": 120},
        {"condition": "bearish_candle", "ce": -0.001, "winrate": 0.48, "samples": 110}
    ])

    best_strategies = [
        {"strategy": "bullish_candle", "CE": 0.002, "winrate": 0.55, "samples": 120}
    ]

    report_text = build_report(
        event_summary=event_summary,
        regime_summary=regime_summary,
        transition_summary=transition_summary,
        ce_table=ce_table,
        best_strategies=best_strategies
    )

    print(report_text)

    save_report(report_text)
    save_ce_table_csv(ce_table)
    save_strategy_csv(best_strategies)

    print("report_generator.py self-test OK")

